; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27027.1 

	TTL	F:\Source_Code\Visual_Studio\Projects\NATIVE\DLL\NativeConsoleAppAids\NativeConssoleAppAids\dllmain.c
	THUMB
	.drectve
	DCB	"-defaultlib:MSVCRTD "
	DCB	"-defaultlib:OLDNAMES "

	EXPORT	|m_hModuleOfThisDLL| [ DATA ]
	EXPORT	|m_hProcHeap| [ DATA ]
	.bss
|m_hModuleOfThisDLL| % 0x4
|m_hProcHeap| %	0x4
	.msvcjmc
|__2CC6E67D_corecrt_stdio_config@h| DCB 0x1
|__05476D76_corecrt_wstdio@h| DCB 0x1
|__A452D4A0_stdio@h| DCB 0x1
|__7B7A869E_ctype@h| DCB 0x1
|__457DD326_basetsd@h| DCB 0x1
|__4384A2D9_corecrt_memcpy_s@h| DCB 0x1
|__4E51A221_corecrt_wstring@h| DCB 0x1
|__2140C079_string@h| DCB 0x1
|__29C54D54_arm_neon@h| DCB 0x1
|__1887E595_winnt@h| DCB 0x1
|__9FC7C64B_processthreadsapi@h| DCB 0x1
|__FA470AEC_memoryapi@h| DCB 0x1
|__F37DAFF1_winerror@h| DCB 0x1
|__7A450CCC_winbase@h| DCB 0x1
|__86261D59_stralign@h| DCB 0x1
|__41381B41_corecrt_wconio@h| DCB 0x1
|__C0802A2B_corecrt_wtime@h| DCB 0x1
|__A40A425D_stat@h| DCB 0x1
|__5A74375D_wchar@h| DCB 0x1
|__6B9C2DC0_tchar@h| DCB 0x1
|__A2A8F82E_dllmain@c| DCB 0x1
	EXPORT	|DllMain|
	EXPORT	|__JustMyCode_Default|
	IMPORT	|__imp_GetProcessHeap|
	IMPORT	|__CheckForDebuggerJustMyCode|
;	COMDAT .pdata
.pdata	SEGMENT
|$pdata1$DllMain| DCD imagerel |DllMain|
	DCD	imagerel |$unwind2$DllMain|
;	COMDAT .xdata
.xdata	SEGMENT
|$unwind2$DllMain| DCD 0x3320001c
	DCD	0xa8fb02
	DCD	0x8802ff04
	DCD	0xff05ef00
;	COMDAT .pdata
.pdata	SEGMENT
|$pdata1$__JustMyCode_Default| DCD imagerel |__JustMyCode_Default|
	DCD	imagerel |$unwind2$__JustMyCode_Default|
;	COMDAT .xdata
.xdata	SEGMENT
|$unwind2$__JustMyCode_Default| DCD 0x10a00005
	DCD	0xff00a8fb
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
.text$mn	SEGMENT

|__JustMyCode_Default| PROC
	push        {r11,lr}
	mov         r11,sp
|$M2|
|$M1|
	pop         {r11,pc}
|$M3|

	ENDP  ; |__JustMyCode_Default|

; Function compile flags: /Odtp
; File f:\source_code\visual_studio\projects\native\dll\nativeconsoleappaids\nativeconssoleappaids\dllmain.c
;	COMDAT DllMain
.text$mn	SEGMENT

|DllMain| PROC

; 9    : {

	push        {r0-r3}
	push        {r11,lr}
	mov         r11,sp
	sub         sp,sp,#8
|$M13|
	ldr         r0,|$LN12@DllMain|			; =|__A2A8F82E_dllmain@c|
	bl          __CheckForDebuggerJustMyCode

; 10   :     switch ( pul_reason_for_call )

	ldr         r3,[sp,#0x14]
	cmp         r3,#1
	beq         |$LN4@DllMain|
	b           |$LN2@DllMain|
|$LN4@DllMain|

; 11   :     {
; 12   : 		case DLL_PROCESS_ATTACH:
; 13   : 			m_hModuleOfThisDLL	= phModule;

	ldr         r2,[sp,#0x10]
	ldr         r3,|$LN11@DllMain|			; =|m_hModuleOfThisDLL|
	str         r2,[r3]

; 14   : 			m_hProcHeap			= GetProcessHeap ( );

	ldr         r3,|$LN10@DllMain|			; =|__imp_GetProcessHeap|
	ldr         r3,[r3]
	blx         r3
	ldr         r3,|$LN9@DllMain|			; =|m_hProcHeap|
	str         r0,[r3]
|$LN2@DllMain|

; 15   : 			break;
; 16   : 
; 17   : 		case DLL_THREAD_ATTACH:
; 18   : 		case DLL_THREAD_DETACH:
; 19   : 		case DLL_PROCESS_DETACH:
; 20   : 			break;
; 21   :     }	// switch ( pul_reason_for_call )
; 22   : 
; 23   :     return TRUE;

	movs        r3,#1
	str         r3,[sp]

; 24   : }	// DllMain

	ldr         r0,[sp]
|$M7|
	add         sp,sp,#8
	pop         {r11}
	ldr         pc,[sp],#0x14
|$LN8@DllMain|
|$LN9@DllMain|
	DCD         |m_hProcHeap|
|$LN10@DllMain|
	DCD         |__imp_GetProcessHeap|
|$LN11@DllMain|
	DCD         |m_hModuleOfThisDLL|
|$LN12@DllMain|
	DCD         |__A2A8F82E_dllmain@c|
|$M14|

	ENDP  ; |DllMain|

	END
