; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27027.1 

	TTL	F:\Source_Code\Visual_Studio\Projects\NATIVE\DLL\NativeConsoleAppAids\NativeConssoleAppAids\ReportLoadStringErrorW.c
	THUMB
	.drectve
	DCB	"-defaultlib:MSVCRTD "
	DCB	"-defaultlib:OLDNAMES "

	.data
	 COMMON	|achrSprintFBuf|, 0x2004

	 COMMON	|achrStringBuf|, 0x2004

	.msvcjmc
|__2CC6E67D_corecrt_stdio_config@h| DCB 0x1
|__05476D76_corecrt_wstdio@h| DCB 0x1
|__A452D4A0_stdio@h| DCB 0x1
|__7B7A869E_ctype@h| DCB 0x1
|__457DD326_basetsd@h| DCB 0x1
|__4384A2D9_corecrt_memcpy_s@h| DCB 0x1
|__4E51A221_corecrt_wstring@h| DCB 0x1
|__2140C079_string@h| DCB 0x1
|__29C54D54_arm_neon@h| DCB 0x1
|__1887E595_winnt@h| DCB 0x1
|__9FC7C64B_processthreadsapi@h| DCB 0x1
|__FA470AEC_memoryapi@h| DCB 0x1
|__F37DAFF1_winerror@h| DCB 0x1
|__7A450CCC_winbase@h| DCB 0x1
|__86261D59_stralign@h| DCB 0x1
|__41381B41_corecrt_wconio@h| DCB 0x1
|__C0802A2B_corecrt_wtime@h| DCB 0x1
|__A40A425D_stat@h| DCB 0x1
|__5A74375D_wchar@h| DCB 0x1
|__6B9C2DC0_tchar@h| DCB 0x1
|__EC73E7AF_reportloadstringerrorw@c| DCB 0x1
	EXPORT	|__local_stdio_printf_options|
	EXPORT	|wprintf|
	EXPORT	|swprintf_s|
	EXPORT	|ReportLoadStringErrorW|
	EXPORT	|__JustMyCode_Default|
	IMPORT	|__imp___acrt_iob_func|
	IMPORT	|__imp___stdio_common_vfwprintf|
	IMPORT	|__imp___stdio_common_vswprintf_s|
	IMPORT	|__imp_GetLastError|
	IMPORT	|__imp_SetLastError|
	IMPORT	|FB_FormatMessageW|
	IMPORT	|FB_FormatMessage2W|
	IMPORT	|GetUnicodeStringPointer|
	IMPORT	|__CheckForDebuggerJustMyCode|
	IMPORT	|m_hModuleOfThisDLL|
	.data
	 COMMON	|?_OptionsStorage@?1??__local_stdio_printf_options@@9@9|, 0x8
							; `__local_stdio_printf_options'::`2'::_OptionsStorage
;	COMDAT .pdata
.pdata	SEGMENT
|$pdata1$__local_stdio_printf_options| DCD imagerel |__local_stdio_printf_options|
	DCD	imagerel |$unwind2$__local_stdio_printf_options|
;	COMDAT .xdata
.xdata	SEGMENT
|$unwind2$__local_stdio_printf_options| DCD 0x32a0000d
	DCD	0xa8fb02
	DCD	0xa802ff
	DCD	0xff
;	COMDAT .pdata
.pdata	SEGMENT
|$pdata1$wprintf| DCD imagerel |wprintf|
	DCD	imagerel |$unwind2$wprintf|
;	COMDAT .xdata
.xdata	SEGMENT
|$unwind2$wprintf| DCD 0x33200030
	DCD	0x10a8fc09
	DCD	0x8809ff04
	DCD	0xff05ef10
;	COMDAT .pdata
.pdata	SEGMENT
|$pdata1$swprintf_s| DCD imagerel |swprintf_s|
	DCD	imagerel |$unwind2$swprintf_s|
;	COMDAT .xdata
.xdata	SEGMENT
|$unwind2$swprintf_s| DCD 0x33200038
	DCD	0x10a8fc0d
	DCD	0x880dff04
	DCD	0xff05ef10
;	COMDAT .pdata
.pdata	SEGMENT
|$pdata1$ReportLoadStringErrorW| DCD imagerel |ReportLoadStringErrorW|
	DCD	imagerel |$unwind2$ReportLoadStringErrorW|
;	COMDAT .xdata
.xdata	SEGMENT
|$unwind2$ReportLoadStringErrorW| DCD 0x33200044
	DCD	0xa8fb06
	DCD	0x8806ff04
	DCD	0xff05ef00
;	COMDAT .pdata
.pdata	SEGMENT
|$pdata1$__JustMyCode_Default| DCD imagerel |__JustMyCode_Default|
	DCD	imagerel |$unwind2$__JustMyCode_Default|
;	COMDAT .xdata
.xdata	SEGMENT
|$unwind2$__JustMyCode_Default| DCD 0x10a00005
	DCD	0xff00a8fb
	.data
|lpSprintFBuf| DCD |achrSprintFBuf|
|lpStringBuf| DCD |achrStringBuf|
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
.text$mn	SEGMENT

|__JustMyCode_Default| PROC
	push        {r11,lr}
	mov         r11,sp
|$M2|
|$M1|
	pop         {r11,pc}
|$M3|

	ENDP  ; |__JustMyCode_Default|

; Function compile flags: /Odtp
; File f:\source_code\visual_studio\projects\native\dll\nativeconsoleappaids\nativeconssoleappaids\reportloadstringerrorw.c
;	COMDAT ReportLoadStringErrorW
.text$mn	SEGMENT

|ReportLoadStringErrorW| PROC

; 30   : {

	push        {r0-r3}
	push        {r11,lr}
	mov         r11,sp
	sub         sp,sp,#0x18
|$M15|
	ldr         r0,|$LN14@ReportLoad|		; =|__EC73E7AF_reportloadstringerrorw@c|
	bl          __CheckForDebuggerJustMyCode

; 31   : 	DWORD dwStatus = GetLastError ( ) ;

	ldr         r3,|$LN13@ReportLoad|		; =|__imp_GetLastError|
	ldr         r3,[r3]
	blx         r3
	str         r0,[sp]

; 32   : 
; 33   : 	if ( dwStatus )

	ldr         r3,[sp]
	cmp         r3,#0
	beq         |$LN2@ReportLoad|

; 34   : 	{
; 35   : 		if ( GetStringPointer ( m_hModuleOfThisDLL ,

	movs        r2,#0
	movs        r1,#0x6F
	ldr         r3,|$LN12@ReportLoad|		; =|m_hModuleOfThisDLL|
	ldr         r0,[r3]
	bl          GetUnicodeStringPointer
	str         r0,[sp,#4]
	ldr         r3,[sp,#4]
	cmp         r3,#0
	beq         |$LN4@ReportLoad|

; 36   : 			                    IDS_STRING111 ,
; 37   : 			                    FB_HIDE_LENGTH ) )
; 38   : 		{
; 39   : 			_stprintf_s ( lpSprintFBuf ,

	ldr         r3,[sp,#0x24]
	ldr         r2,|$LN10@ReportLoad|		; =|lpStringBuf|
	ldr         r2,[r2]
	mov         r1,#0x1002
	ldr         r0,|$LN11@ReportLoad|		; =|lpSprintFBuf|
	ldr         r0,[r0]
	bl          swprintf_s

; 40   : 				          RCDATA_MAX_BUFFER_P6C ,
; 41   : 				          lpStringBuf ,
; 42   : 				          puintStringID ) ;
; 43   : 			_tprintf ( FB_FormatMessage ( lpStringBuf ,

	movs        r2,#0
	ldr         r1,[sp]
	ldr         r3,|$LN10@ReportLoad|		; =|lpStringBuf|
	ldr         r0,[r3]
	bl          FB_FormatMessageW
	str         r0,[sp,#8]
	ldr         r0,[sp,#8]
	bl          wprintf
|$LN4@ReportLoad|

; 44   : 				                          dwStatus ,
; 45   : 				                          SCF2_HEXADECIMAL ) ) ;
; 46   : 		}   // if ( GetStringPointer ( m_hModuleOfThisDLL , IDS_STRING111 , FB_HIDE_LENGTH ) )
; 47   : 	}   // TRUE block, if ( dwStatus )

	b           |$LN3@ReportLoad|
|$LN2@ReportLoad|

; 48   : 	else
; 49   : 	{	// Since Windows provided no error, we supply our own.
; 50   : 		dwStatus = FB_ERR_STRNG_NOT_FOUND_FOR_ID ;

	ldr         r3,|$LN9@ReportLoad|		; =0x20020010
	str         r3,[sp]

; 51   : 		SetLastError ( dwStatus );

	ldr         r0,[sp]
	ldr         r3,|$LN8@ReportLoad|		; =|__imp_SetLastError|
	ldr         r3,[r3]
	blx         r3

; 52   : 		_tprintf ( FB_FormatMessage2 ( IDS_STRING111 ,

	movs        r2,#0
	ldr         r1,[sp]
	movs        r0,#0x6F
	bl          FB_FormatMessage2W
	str         r0,[sp,#0xC]
	ldr         r0,[sp,#0xC]
	bl          wprintf
|$LN3@ReportLoad|

; 53   :   			                           dwStatus ,
; 54   : 				                       SCF2_HEXADECIMAL ) ) ;
; 55   : 	}   // FALSE block, if ( dwStatus )
; 56   : 
; 57   : 	//	------------------------------------------------------------------------
; 58   : 	//	Raise a structured exception if the SEH flag is set. When this happens,
; 59   : 	//	there is no actual return, and the stack is unwound.
; 60   : 	//	------------------------------------------------------------------------
; 61   : 
; 62   : 	return dwStatus ;	// Tell the calling routine to call GetLastError and/or FB_GetlpErrMsgSprintf (to get the message).

	ldr         r3,[sp]
	str         r3,[sp,#0x10]

; 63   : }	// ReportLoadStringErrorW

	ldr         r0,[sp,#0x10]
|$M6|
	add         sp,sp,#0x18
	pop         {r11}
	ldr         pc,[sp],#0x14
|$LN7@ReportLoad|
|$LN8@ReportLoad|
	DCD         |__imp_SetLastError|
|$LN9@ReportLoad|
	DCD         0x20020010
|$LN10@ReportLoad|
	DCD         |lpStringBuf|
|$LN11@ReportLoad|
	DCD         |lpSprintFBuf|
|$LN12@ReportLoad|
	DCD         |m_hModuleOfThisDLL|
|$LN13@ReportLoad|
	DCD         |__imp_GetLastError|
|$LN14@ReportLoad|
	DCD         |__EC73E7AF_reportloadstringerrorw@c|
|$M16|

	ENDP  ; |ReportLoadStringErrorW|

; Function compile flags: /Odtp
; File c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\corecrt_wstdio.h
;	COMDAT swprintf_s
.text$mn	SEGMENT

|swprintf_s| PROC

; 1538 :         {

	push        {r0-r3}
	push        {r4,r11,lr}
	add         r11,sp,#4
	sub         sp,sp,#0x34
|$M11|
	ldr         r0,|$LN10@swprintf_s|		; =|__05476D76_corecrt_wstdio@h|
	bl          __CheckForDebuggerJustMyCode

; 1539 :             int _Result;
; 1540 :             va_list _ArgList;
; 1541 :             __crt_va_start(_ArgList, _Format);

	add         r3,sp,#0x48
	adds        r3,r3,#4
	str         r3,[sp,#0x1C]

; 1542 :             _Result = _vswprintf_s_l(_Buffer, _BufferCount, _Format, NULL, _ArgList);

	ldr         r3,[sp,#0x48]
	str         r3,[sp,#0x20]

; 1265 :         int const _Result = __stdio_common_vswprintf_s(

	bl          __local_stdio_printf_options
	str         r0,[sp,#0x10]
	ldr         r3,[sp,#0x1C]
	str         r3,[sp,#8]
	movs        r3,#0
	str         r3,[sp,#4]
	ldr         r3,[sp,#0x20]
	str         r3,[sp]
	ldr         r3,[sp,#0x44]
	ldr         r2,[sp,#0x40]
	ldr         r1,[sp,#0x10]
	ldr         r0,[r1]
	ldr         r1,[sp,#0x10]
	ldr         r1,[r1,#4]
	ldr         r4,|$LN9@swprintf_s|		; =|__imp___stdio_common_vswprintf_s|
	ldr         r4,[r4]
	blx         r4
	str         r0,[sp,#0x24]
	ldr         r3,[sp,#0x24]
	str         r3,[sp,#0x14]

; 1266 :             _CRT_INTERNAL_LOCAL_PRINTF_OPTIONS,
; 1267 :             _Buffer, _BufferCount, _Format, _Locale, _ArgList);
; 1268 : 
; 1269 :         return _Result < 0 ? -1 : _Result;

	ldr         r3,[sp,#0x14]
	cmp         r3,#0
	bge         |$LN5@swprintf_s|
	mvn         r3,#0
	str         r3,[sp,#0x18]
	b           |$LN6@swprintf_s|
|$LN5@swprintf_s|
	ldr         r3,[sp,#0x14]
	str         r3,[sp,#0x18]
|$LN6@swprintf_s|

; 1542 :             _Result = _vswprintf_s_l(_Buffer, _BufferCount, _Format, NULL, _ArgList);

	ldr         r3,[sp,#0x18]
	str         r3,[sp,#0x28]

; 1543 :             __crt_va_end(_ArgList);

	movs        r3,#0
	str         r3,[sp,#0x1C]

; 1544 :             return _Result;

	ldr         r3,[sp,#0x28]
	str         r3,[sp,#0x2C]

; 1545 :         }

	ldr         r0,[sp,#0x2C]
|$M7|
	add         sp,sp,#0x34
	pop         {r4,r11}
	ldr         pc,[sp],#0x14
|$LN8@swprintf_s|
|$LN9@swprintf_s|
	DCD         |__imp___stdio_common_vswprintf_s|
|$LN10@swprintf_s|
	DCD         |__05476D76_corecrt_wstdio@h|
|$M12|

	ENDP  ; |swprintf_s|

; Function compile flags: /Odtp
; File c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\corecrt_wstdio.h
;	COMDAT wprintf
.text$mn	SEGMENT

|wprintf| PROC

; 611  :     {

	push        {r0-r3}
	push        {r4,r11,lr}
	add         r11,sp,#4
	sub         sp,sp,#0x24
|$M10|
	ldr         r0,|$LN9@wprintf|			; =|__05476D76_corecrt_wstdio@h|
	bl          __CheckForDebuggerJustMyCode

; 612  :         int _Result;
; 613  :         va_list _ArgList;
; 614  :         __crt_va_start(_ArgList, _Format);

	add         r3,sp,#0x30
	adds        r3,r3,#4
	str         r3,[sp,#0xC]

; 615  :         _Result = _vfwprintf_l(stdout, _Format, NULL, _ArgList);

	movs        r0,#1
	ldr         r3,|$LN8@wprintf|			; =|__imp___acrt_iob_func|
	ldr         r3,[r3]
	blx         r3
	str         r0,[sp,#0x14]
	ldr         r3,[sp,#0x30]
	str         r3,[sp,#0x10]

; 306  :         return __stdio_common_vfwprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	bl          __local_stdio_printf_options
	str         r0,[sp,#8]
	ldr         r3,[sp,#0xC]
	str         r3,[sp,#4]
	movs        r3,#0
	str         r3,[sp]
	ldr         r3,[sp,#0x10]
	ldr         r2,[sp,#0x14]
	ldr         r1,[sp,#8]
	ldr         r0,[r1]
	ldr         r1,[sp,#8]
	ldr         r1,[r1,#4]
	ldr         r4,|$LN7@wprintf|			; =|__imp___stdio_common_vfwprintf|
	ldr         r4,[r4]
	blx         r4
	str         r0,[sp,#0x18]

; 615  :         _Result = _vfwprintf_l(stdout, _Format, NULL, _ArgList);

	ldr         r3,[sp,#0x18]
	str         r3,[sp,#0x1C]

; 616  :         __crt_va_end(_ArgList);

	movs        r3,#0
	str         r3,[sp,#0xC]

; 617  :         return _Result;

	ldr         r3,[sp,#0x1C]
	str         r3,[sp,#0x20]

; 618  :     }

	ldr         r0,[sp,#0x20]
|$M5|
	add         sp,sp,#0x24
	pop         {r4,r11}
	ldr         pc,[sp],#0x14
|$LN6@wprintf|
|$LN7@wprintf|
	DCD         |__imp___stdio_common_vfwprintf|
|$LN8@wprintf|
	DCD         |__imp___acrt_iob_func|
|$LN9@wprintf|
	DCD         |__05476D76_corecrt_wstdio@h|
|$M11|

	ENDP  ; |wprintf|

; Function compile flags: /Odtp
; File c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
;	COMDAT __local_stdio_printf_options
.text$mn	SEGMENT

|__local_stdio_printf_options| PROC

; 86   :     {

	push        {r11,lr}
	mov         r11,sp
	sub         sp,sp,#8
|$M9|
	ldr         r0,|$LN6@local_stdi|		; =|__2CC6E67D_corecrt_stdio_config@h|
	bl          __CheckForDebuggerJustMyCode

; 87   :         static unsigned __int64 _OptionsStorage;
; 88   :         return &_OptionsStorage;

	ldr         r3,|$LN5@local_stdi|		; =|?_OptionsStorage@?1??__local_stdio_printf_options@@9@9|
	str         r3,[sp]

; 89   :     }

	ldr         r0,[sp]
|$M3|
	add         sp,sp,#8
	pop         {r11,pc}
|$LN7@local_stdi|
|$M8|
	__debugbreak
|$LN4@local_stdi|
|$LN5@local_stdi|
	DCD         |?_OptionsStorage@?1??__local_stdio_printf_options@@9@9|
|$LN6@local_stdi|
	DCD         |__2CC6E67D_corecrt_stdio_config@h|
|$M10|

	ENDP  ; |__local_stdio_printf_options|

	END
